basePath: /v1
definitions:
  requests.CreateUserRequest:
    properties:
      emailAddress:
        type: string
      id:
        type: string
      password:
        type: string
    type: object
  rest.Error:
    properties:
      message:
        type: string
      slug:
        type: string
    type: object
  rest.User:
    properties:
      emailAddress:
        type: string
      id:
        type: string
    type: object
  rest.Users:
    properties:
      users:
        items:
          $ref: '#/definitions/rest.User'
        type: array
    type: object
host: petstore.swagger.io
info:
  contact:
    email: support@todo.io
    name: TODO
    url: http://todo.io/support
  description: TODO.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://todo.io/terms
  title: Message Board Identity Api
  version: "1.0"
paths:
  /api/users:
    get:
      consumes:
      - application/json
      description: get users
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/rest.Users'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/rest.Error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/rest.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/rest.Error'
      summary: List users
      tags:
      - users
    post:
      consumes:
      - application/json
      description: create user
      parameters:
      - description: Create user
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/requests.CreateUserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/rest.User'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/rest.Error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/rest.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/rest.Error'
      summary: Create user
      tags:
      - users
  /api/users/{id}:
    get:
      consumes:
      - application/json
      description: get user by id
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/rest.User'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/rest.Error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/rest.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/rest.Error'
      summary: Get user
      tags:
      - users
swagger: "2.0"
